services:
  tbtc-relayer-dev:
    environment:
      API_ONLY_MODE: true
      VERBOSE_APP: true
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    build:
      target: production
    command: node dist/index.js
    volumes: [] # Avoid volumes from the base docker-compose.yml
