services:
  tbtc-relayer-dev:
    environment:
      NODE_ENV: test
      API_ONLY_MODE: true
      VERBOSE_APP: true
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      
      # Mock private keys for CI validation (safe test values)
      CHAIN_SEPOLIATESTNET_PRIVATE_KEY: "0x1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef"
      CHAIN_ARBITRUMMAINNET_PRIVATE_KEY: "0x1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef"
      CHAIN_BASEMAINNET_PRIVATE_KEY: "0x1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef"
      CHAIN_BASESEPOLIATESTNET_PRIVATE_KEY: "0x1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef"
      CHAIN_SOLANADEVNET_PRIVATE_KEY: "5KQwrPbwdL6PhXujxW37FSSQZ1JiwsST4cqQzDeyXtP79zkvFD3"
      CHAIN_STARKNETTESTNET_PRIVATE_KEY: "0x1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef"
      CHAIN_SUITESTNET_PRIVATE_KEY: "0x1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef"
      CHAIN_SOLANADEVNETIMPORTED_SOLANA_PRIVATE_KEY: "5KQwrPbwdL6PhXujxW37FSSQZ1JiwsST4cqQzDeyXtP79zkvFD3"
      
      # Mock RPC URLs for CI validation
      ETHEREUM_MAINNET_RPC: "https://mock-ethereum-mainnet.test.com"
      CHAIN_SOLANADEVNETIMPORTED_L2_RPC: "https://mock-solana-devnet.test.com"
      CHAIN_SOLANADEVNETIMPORTED_L2_WS_RPC: "wss://mock-solana-devnet-ws.test.com"
      
    build:
      target: development
    command: node dist/index.js
    volumes: [] # Avoid volumes from the base docker-compose.yml
