name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"

      - name: Install dependencies
        run: |
          echo "yarn version:"
          yarn --version
          echo "node version:"
          node --version
          yarn install --frozen-lockfile --ignore-optional

      # TODO: Enable those after fixing the linting errors

      # - name: Lint
        # run: yarn lint

      # - name: Format check
        # run: yarn format
        
      - name: Detect unused dependencies
        run: yarn depcheck

      - name: Build
        run: yarn build

      - name: Run tests
        run: yarn test:coverage

      - name: Upload coverage as artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage/
          retention-days: 7
